services:
  - type: web
    name: viztalk-ai-tutor-backend
    runtime: docker
    plan: free
    region: oregon
    branch: main
    rootDir: ./backend
    dockerCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: GROQ_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGO_URI
        sync: false
